name: minos_conda_micromamba
channels:
  - conda-forge
  - defaults
dependencies: # Added pip and python at top to avoid conda giving grumpy warnings
  #- pip
  - python_abi=3.9=*cp*
  - python~=3.9
  #- conda-forge::conda- # For alternative method of "conda build ."; required conda-build to be installed
  - r-base
  - r-sf
  - r-dplyr
  - r-tidyverse
  - r-argparse
  - r-ordinal
  - r-nnet
  - r-pscl
  - r-geojsonsf
  - r-sp
  - r-sf
  - r-dplyr
  - r-tidyverse
  - r-argparse
  - r-ordinal
  - r-nnet
  - r-pscl
  - r-geojsonsf
  - r-sp
  - r-texreg
  - r-shadowtext
  - r-lme4
  - r-VGAM
  - r-bestNormalize
  - r-here
  - r-scales
  - r-ggextra
  - r-ggridges
  - r-gghighlight
  - r-shadowtext
  - r-lme4
  - r-VGAM
  - r-bestNormalize
  - r-here
  - r-scales
  - r-ggextra
  - r-ggridges
  - r-gghighlight
  - r-randomForest
  - r-parallelly
  - r-doParallel
  - r-caret
  - r-GLMMadaptive
  - r-parallelly
  - r-doParallel
  - r-caret
  - r-GLMMadaptive
  - r-ranger
  - pandoc
  - sphinx
  - myst-parser
  - gcc
  - rpy2
  - setuptools
  - seaborn
  - pandoc
  - sphinx
  - myst-parser
  - gcc
 # Same packages as were in "requirements.txt" except minos and vivarium, as both installed during "make install"
  - pip:
    - pyyaml>=5.4
    - pytest~=6.0.1
    - striprtf
    - scikit-learn
    - geojson
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - geopandas
    - topojson
    - striprtf
    - scikit-learn
    - geojson
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - geopandas
    - topojson
    - uuid
    - distutils_pytest
    #- vivarium~=0.10.12 # Can install here, but KeyError issue is then missed during "make install"
    - pandas==1.4.4
    - numpy==1.22.4
    - matplotlib
prefix: