# install any packages here that are needed.
install.packages("ordinal", repos = "http://cran.us.r-project.org")
install.packages('nnet', repos = "http://cran.us.r-project.org")
install.packages('tidyverse', repos = "http://cran.us.r-project.org")
install.packages('stringr', repos = "http://cran.us.r-project.org")
install.packages('readr', repos = "http://cran.us.r-project.org")
install.packages('pscl', repos = "http://cran.us.r-project.org")
install.packages('ggplot2', repos = "http://cran.us.r-project.org")
install.packages('texreg', repos = "http://cran.us.r-project.org")
install.packages('geojsonsf', repos="http://cran.us.r-project.org")
install.packages('broom', repos="http://cran.us.r-project.org")
install.packages('sf', repos="http://cran.us.r-project.org")
install.packages('sp', repos="http://cran.us.r-project.org")
install.packages('tibble', repos="http://cran.us.r-project.org")
install.packages('argparse', repos="http://cran.us.r-project.org")
#
