---
title: "Child Poverty Reduction Interventions"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    df_print: paged
    code_folding: hide
---

# SETUP

```{r "setup", include=FALSE}

require(tidyverse)
require(ggplot2)
require(knitr)
require(here)
require(dplyr)
require(tidyr)
require(purrr)

#workingDir <- "/home/luke/Documents/WORK/MINOS/"
workingDir <- normalizePath('../')
knitr::opts_knit$set(root.dir = workingDir)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
rm(workingDir)
```

Source utils for some functions.

```{r}
source(here::here('minos', 'utils_datain.R'))
#source(here::here('minos', 'utils_validation_vis.R'))
#source(here::here('minos', 'validation', 'utils.r'))
```


```{r}
out.path <- here::here('output', 'default_config')

# define subset of variables to reduce size of batch output
var.list <- c('pidp', 'hidp', 'time', 'weight', 
              'age', 'ethnicity', 'education_state', 'region', 
              'hh_income',
              'housing_quality', 'neighbourhood_safety', 'loneliness', 'ncigs', 'nutrition_quality', 'financial_situation', 'urban', 'housing_tenure',
              'SF_12', 'matdep_child')

base <- read_output(out.path, 
                        scenario = 'baseline', 
                        var.list = var.list,
                        verbose = TRUE)
int <- read_output(out.path, 
                            scenario = 'ChildPovertyReductionSUSTAIN', 
                            var.list = var.list,
                            verbose = TRUE)
```

# PLOTS

## Relative Poverty

### Threshold

Relative poverty is defined as the proportion of children living in households with income below 60% of the population median *in a given year*.

For our starting year of 2020:

```{r, echo=FALSE}
base.2020 <- base %>%
  filter(time == 2020)

mean.hh_income <- weighted.mean(base.2020$hh_income, w = base.2020$weight)
rel.pov.threshold <- mean.hh_income * 0.6

print(paste0("Relative poverty threshold in 2020: ", rel.pov.threshold))
rm(base.2020, mean.hh_income, rel.pov.threshold)
```

Then looking at how this threshold changes over the length of our simulation:

```{r, echo=FALSE}
threshold <- base %>%
  select(time, weight, hh_income) %>%
  group_by(time) %>%
  summarise(poverty_threshold = (weighted.mean(hh_income, w = weight) * 0.6))

ggplot(data = threshold, aes(x = time, y = poverty_threshold)) +
  geom_col() +
  geom_hline(yintercept = threshold$poverty_threshold[threshold$time == 2020], linetype='dashed') +
  labs(title = 'Relative poverty threshold over time') +
  xlab('Year') +
  ylab('Threshold')
```

### MCS - Whole Pop

```{r}
full.sample.change.SF12 <- function(base.dat, int.dat) {
  base.all.SF12 <- base.dat %>%
    select(time, weight, SF_12) %>%
    group_by(time) %>%
    summarise(base.SF12 = weighted.mean(SF_12, w = weight))
  
  int.all.SF12 <- int.dat %>%
    select(time, weight, SF_12) %>%
    group_by(time) %>%
    summarise(int.SF12 = weighted.mean(SF_12, w = weight))
  
  combined <- merge(x = base.all.SF12, y = int.all.SF12, by = 'time')
  combined$diff <- combined$int.SF12 - combined$base.SF12
  
  ggplot(combined, aes(x = time, y = diff)) +
    geom_line() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12') +
    xlab('Year') +
    ylab('Difference')
}

full.sample.change.SF12(base, int)
```


## DIAGNOSTICS

```{r}
sample_information <- function(int.dat, target.year) {
  hh_boosted <- int.dat %>%
    select(hidp, time, income_boosted, boost_amount, nkids) %>%
    filter(income_boosted == 'True') %>%
    group_by(time) %>%
    summarise(n_boosted = length(unique(hidp)),
              total_boost = sum(boost_amount),
              kids_boosted = sum(nkids))
  
  p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Number of households receiving intervention') +
    xlab('Year') +
    ylab('Number Boosted')
  
  p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Number of children in households receiving intervention') +
    xlab('Year') +
    ylab('Number Children')
  
  p3 <- ggplot(hh_boosted, aes(x = time, y = total_boost)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Total boost amount') +
    xlab('Year') +
    ylab('Boost Amount')
  
  mean.boost <- int.dat %>%
    select(time, income_boosted, boost_amount) %>%
    group_by(time, income_boosted) %>%
    summarise(mean_boost = mean(boost_amount)) %>%
    filter(income_boosted == 'True')
  
  p4 <- ggplot(mean.boost, aes(x = time, y = mean_boost)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Mean boost amount') +
    xlab('Year') +
    ylab('Boost Amount')
  
  print(p1)
  print(p2)
  print(p3)
  print(p4)
}

sample_information(int, target.year = 2030)
```

