---
title: "Diagnosing Child Poverty Reduction Interventions"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    df_print: paged
    code_folding: hide
---

# SETUP

This document presents results from a host of interventions on child poverty, including visualisations of the change in SF_12_MCS compared with baseline.

```{r "setup", include=FALSE}

library(tidyverse)
library(ggplot2)
library(ggridges) # for densities over time plots. 
library(knitr)
library(here)
library(gghighlight)

workingDir <- "/home/luke/Documents/MINOS/Minos/"
#workingDir <- normalizePath('../')
knitr::opts_knit$set(root.dir = workingDir)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
rm(workingDir)
```

```{r "imports", include=FALSE}
source(here::here('minos', 'utils_datain.R'))
#source(here::here('minos', 'utils_validation_vis.R'))
source(here::here('minos', 'validation', 'utils.r'))
```

```{r, include=FALSE}
out.path <- here::here('output', 'default_config/')
base.dat <- read_singular_local_out(out.path, 
                                    'baseline', 
                                    drop.dead = TRUE, 
                                    drop.zero.weight = TRUE)
rel.int <- read_singular_local_out(out.path, 
                                   'ChildPovertyReductionRELATIVE', 
                                   drop.dead = TRUE,
                                   drop.zero.weight = TRUE)
rel.int.2 <- read_singular_local_out(out.path,
                                     'ChildPovertyReductionRELATIVE_2',
                                     drop.dead = TRUE,
                                     drop.zero.weight = TRUE)
abs.int <- read_singular_local_out(out.path, 
                                   'ChildPovertyReductionABSOLUTE', 
                                   drop.dead = TRUE,
                                   drop.zero.weight = TRUE)
```

# Household Income

i.e. is the intervention working?

## All Pop

```{r}
base.inc <- base.dat %>%
  select(pidp, hidp, time, hh_income, weight) %>%
  group_by(time) %>%
  summarise(hh_income = weighted.mean(x = hh_income,w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Baseline')

rel.inc <- rel.int %>%
  select(pidp, hidp, time, hh_income, weight) %>%
  group_by(time) %>%
  summarise(hh_income = weighted.mean(x = hh_income,w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Relative')

inc <- rbind(base.inc, rel.inc)

ggplot(inc, aes(x = time, y = hh_income, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(base.dat, aes(x = hh_income, y = time, group = time, color = 'blue', alpha = 0.3)) +
  geom_density_ridges() +
  geom_density_ridges(data = rel.int, aes(x = hh_income, y = time, group = time, color = 'red')) +
  theme(legend.position = 'none') +
  labs(title = 'Relative Poverty Reduction Intervention - Red')
```

## Households With Children

```{r}
base.inc <- base.dat %>%
  select(pidp, hidp, time, hh_income, age, nkids, weight) %>%
  mutate(nkids_any = (nkids > 0)) %>%
  filter(nkids_any == TRUE) %>%
  group_by(time) %>%
  summarise(hh_income = weighted.mean(x = hh_income, w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Baseline')

rel.inc <- rel.int %>%
  select(pidp, hidp, time, hh_income, age, nkids, weight) %>%
  mutate(nkids_any = (nkids > 0)) %>%
  filter(nkids_any = TRUE) %>%
  group_by(time) %>%
  summarise(hh_income = weighted.mean(x = hh_income, w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Relative')

inc <- rbind(base.inc, rel.inc)

ggplot(inc, aes(x = time, y = hh_income, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()
```

## Boosted Pop

```{r}
boosted.pidps <- rel.int %>%
  filter(income_boosted == 'True') %>%
  select(pidp)

base.inc <- base.dat %>%
  select(pidp, hidp, time, hh_income, SF_12, weight) %>%
  filter(pidp %in% boosted.pidps$pidp) %>%
  group_by(time) %>%
  summarise(hh_income = weighted.mean(x = hh_income, w = weight, na.rm = TRUE),
            SF_12 = weighted.mean(x = SF_12, w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Baseline')

rel.inc <- rel.int %>%
  select(pidp, hidp, time, hh_income, SF_12, weight) %>%
  filter(pidp %in% boosted.pidps$pidp) %>%
  group_by(time) %>%
  summarise(hh_income = weighted.mean(x = hh_income, w = weight, na.rm = TRUE),
            SF_12 = weighted.mean(x = SF_12, w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Relative')

inc <- rbind(base.inc, rel.inc)

ggplot(inc, aes(x = time, y = hh_income, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = SF_12, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()
```





# TESTING THE BOOSTED POP

```{r}
boosted.pidps <- rel.int %>%
  filter(income_boosted == 'True') %>%
  select(pidp)

# Define the recoding mapping for housing_quality
recoding_mapping <- c("Low" = 1, "Medium" = 2, "High" = 3)  # Adjust as needed

base.inc <- base.dat %>%
  select(pidp, hidp, time, age, hh_income, SF_12, housing_quality, neighbourhood_safety, ncigs, nutrition_quality, loneliness, nkids, weight) %>%
  filter(pidp %in% boosted.pidps$pidp) %>%
  mutate_at(vars(housing_quality), ~recode(., !!!recoding_mapping)) %>%
  group_by(time) %>%
  summarise(boosted_pop = n(),
            age = mean(age, na.rm = TRUE),
            hh_income = weighted.mean(x = hh_income, w = weight, na.rm = TRUE),
            SF_12 = weighted.mean(x = SF_12, w = weight, na.rm = TRUE),
            housing_quality = weighted.mean(x = housing_quality, w = weight, na.rm = TRUE),
            neighbourhood_safety = weighted.mean(x = neighbourhood_safety, w = weight, na.rm = TRUE),
            ncigs = weighted.mean(x = ncigs, w = weight, na.rm = TRUE),
            nutrition_quality = weighted.mean(x = nutrition_quality, w = weight, na.rm = TRUE),
            loneliness = weighted.mean(x = loneliness, w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Baseline')


rel.inc <- rel.int %>%
  select(pidp, hidp, time, age, hh_income, SF_12, housing_quality, neighbourhood_safety, ncigs, nutrition_quality, loneliness, nkids, weight) %>%
  filter(pidp %in% boosted.pidps$pidp) %>%
  mutate_at(vars(housing_quality), ~recode(., !!!recoding_mapping)) %>%
  group_by(time) %>%
  summarise(boosted_pop = n(),
            age = mean(age, na.rm = TRUE),
            hh_income = weighted.mean(x = hh_income, w = weight, na.rm = TRUE),
            SF_12 = weighted.mean(x = SF_12, w = weight, na.rm = TRUE),
            housing_quality = weighted.mean(x = housing_quality, w = weight, na.rm = TRUE),
            neighbourhood_safety = weighted.mean(x = neighbourhood_safety, w = weight, na.rm = TRUE),
            ncigs = weighted.mean(x = ncigs, w = weight, na.rm = TRUE),
            nutrition_quality = weighted.mean(x = nutrition_quality, w = weight, na.rm = TRUE),
            loneliness = weighted.mean(x = loneliness, w = weight, na.rm = TRUE)) %>%
  mutate(scen = 'Relative')

base.treated <- base.dat %>%
  select(pidp, time, hh_income) %>%
  filter(pidp %in% boosted.pidps$pidp)

rel.treated <- rel.int %>%
  select(pidp, time, hh_income) %>%
  filter(pidp %in% boosted.pidps$pidp)

inc <- rbind(base.inc, rel.inc)
```

```{r}
ggplot(inc, aes(x = time, y = boosted_pop, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = age, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = hh_income, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(base.treated, aes(x = hh_income, y = time, group = time, color = 'blue', alpha = 0.3)) +
  geom_density_ridges() +
  geom_density_ridges(data = rel.treated, aes(x = hh_income, y = time, group = time, color = 'red')) +
  theme(legend.position = 'none') +
  labs(title = 'Relative Poverty Reduction Intervention - Red')

ggplot(inc, aes(x = time, y = SF_12, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = housing_quality, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = neighbourhood_safety, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = ncigs, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = nutrition_quality, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

ggplot(inc, aes(x = time, y = loneliness, group = scen, color = scen, fill = scen)) +
  geom_line() +
  geom_point()

```










```{r}

```








