---
title: "Scottish Child Payment Interventions"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    df_print: paged
    code_folding: hide
---

# SETUP

```{r "setup", include=FALSE}

require(tidyverse)
require(ggplot2)
require(knitr)
require(here)
require(dplyr)
require(tidyr)
require(purrr)

#workingDir <- "/home/luke/Documents/WORK/MINOS/"
workingDir <- normalizePath('../')
knitr::opts_knit$set(root.dir = workingDir)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
rm(workingDir)
```

Source utils for some functions.

```{r source_functions, include=FALSE}
source(here::here('minos', 'utils_datain.R'))
```


```{r read_data}
#out.path <- here::here('output', 'default_config')
#out.path <- here::here('output', 'glasgow_scaled')
out.path <- here::here('output', 'scaled_scotland')


# define subset of variables to reduce size of batch output
var.list <- c('pidp', 'hidp', 'time', 'weight', 
              'age', 'ethnicity', 'region', 'nkids', 'nkids_ind', 'S7_labour_state',
              'hh_income', 'child_ages', 'simd_decile',
              'SF_12', 'matdep_child')

base <- read_output(out.path, 
                    scenario = 'baseline', 
                    var.list = var.list,
                    verbose = TRUE)
int25 <- read_output(out.path, 
                      scenario = '25UniversalCredit', 
                      var.list = var.list,
                      verbose = TRUE)
int30 <- read_output(out.path,
                      scenario = '30UniversalCredit',
                      var.list = var.list,
                      verbose = TRUE)
int35 <- read_output(out.path,
                      scenario = '35UniversalCredit',
                      var.list = var.list,
                      verbose = TRUE)
int40 <- read_output(out.path,
                      scenario = '40UniversalCredit',
                      var.list = var.list,
                      verbose = TRUE)
int45 <- read_output(out.path,
                      scenario = '45UniversalCredit',
                      var.list = var.list,
                      verbose = TRUE)
int50 <- read_output(out.path,
                      scenario = '50UniversalCredit',
                      var.list = var.list,
                      verbose = TRUE)

#int.list <- c(int25, int30, int35, int40, int45, int50)
int.list <- list(base, int25, int30, int35, int40, int45, int50)
scen.list <- c('base', 'int25', 'int30', 'int35', 'int40', 'int45', 'int50')

# set up a boolean tag for batch or not
# this is necessary because batch runs need slightly different processing before visualisation
if ('run_id' %in% names(base)) {
  batch <- TRUE
} else {
  batch <- FALSE
}

# Save path and save flag
save.path <- here::here('plots', 'SCOTGOV', 'CPR')
create.if.not.exists(save.path)
shall.we.save <- FALSE
plot.width <- 10
plot.height <- 5
```


# FUNCTIONS

```{r SF12_whole_pop, echo=FALSE}
SF12.change.full.sample.single <- function(df.list, scen.list) {
  single.mean <- function(data, scen) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, SF_12) %>%
      group_by(time) %>%
      summarise(!!newvar.name := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  df.list <- mapply(single.mean, df.list, scen.list, SIMPLIFY = FALSE)
  
  combined <- df.list %>%
    reduce(full_join, by='time')

  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  #return(combined)
  
  scen.list <- scen.list[-1]
  
  #TODO: Rename factor levels
  #correct factor levels for plot
  # combined$scen <- factor(combined$scen,
  #                         levels = scen.list)
  
  #return(combined)
  
  p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
    geom_line() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12 MCS', subtitle = 'Whole population') +
    xlab('Year') +
    ylab('Difference')
  
  print(p1)
}

SF12.change.full.sample.batch <- function(df.list, scen.list) {
  batch.mean <- function(data, scen) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, run_id, SF_12) %>%
      group_by(time, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  # base <- batch.mean(base.dat, scen = 'base')
  # int1 <- batch.mean(int.dat1, scen = 'int25')
  # int2 <- batch.mean(int.dat2, scen = 'int50')
  # int3 <- batch.mean(int.dat3, scen = 'int75')
  # int4 <- batch.mean(int.dat4, scen = 'int100')
  
  df.list <- mapply(single.mean, df.list, scen.list, SIMPLIFY = FALSE)
  
  #df.list <- list(base, int1, int2, int3, int4)
  combined <- df.list %>%
    reduce(full_join, by=c('time', 'run_id'))

  # combined$diff25 <- combined$int25.SF12 - combined$base.SF12
  # combined$diff50 <- combined$int50.SF12 - combined$base.SF12
  # combined$diff75 <- combined$int75.SF12 - combined$base.SF12
  # combined$diff100 <- combined$int100.SF12 - combined$base.SF12
  
  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')

  # combined <- combined %>%
  #   select(time, run_id, contains('diff')) %>%
  #   pivot_longer(cols = diff25:diff100,
  #                names_to = 'scen',
  #                values_to = 'diff')
  
  # TODO: Rename factor levels
  # correct factor levels for plot
  # combined$scen <- factor(combined$scen,
  #                         levels = c('diff100', 'diff75', 'diff50', 'diff25'))
  
  p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
    geom_smooth() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12 MCS', subtitle = 'Whole population') +
    xlab('Year') +
    ylab('Difference')
  
  print(p1)
}
```

```{r SF12_families, echo=FALSE}
SF12.change.families.single <- function(df.list, scen.list) {
  single.mean <- function(data, scen) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, SF_12, nkids) %>%
      filter(nkids > 0) %>%
      group_by(time) %>%
      summarise(!!newvar.name := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  df.list <- mapply(single.mean, df.list, scen.list, SIMPLIFY = FALSE)
  
  combined <- df.list %>%
    reduce(full_join, by='time')

  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
    geom_line() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12 MCS', subtitle = 'Households with Children') +
    xlab('Year') +
    ylab('Difference')
  
  print(p1)
}

SF12.change.families.batch <- function(df.list, scen.list) {
  batch.mean <- function(data, scen) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, run_id, SF_12, nkids) %>%
      filter(nkids > 0) %>%
      group_by(time, run_id) %>%
      summarise(!!newvar.name := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  df.list <- mapply(batch.mean, df.list, scen.list, SIMPLIFY = FALSE)
  
  combined <- df.list %>%
    reduce(full_join, by=c('time', 'run_id'))

  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
    geom_smooth() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12 MCS', subtitle = 'Households with Children') +
    xlab('Year') +
    ylab('Difference')
  
  print(p1)
}
```

```{r SF12_treated, echo=FALSE}
SF12.change.treated.single <- function(df.list, scen.list) {
  single.mean <- function(data, scen, boosted) {
    # define varname
    newvar.name <- paste0(scen, '.SF12')
    # prepare data
    data <- data %>%
      select(pidp, time, weight, SF_12) %>%
      filter(pidp %in% boosted) %>%
      group_by(time) %>%
      summarise(!!newvar.name := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  #TODO: FIX THIS! NEED DIFFERENT BASELINE FOR EACH INT?? THINK SO!
  # NEED A FUNCTION TO DO THE DIFF CALCULATION AND ANOTHER TO RUN IT THROUGH
  # EACH DF
  # get boosted pidps
  boosted <- df.list[[2]] %>%
    select(pidp, income_boosted) %>%
    filter(income_boosted == 'True')
  rm(tmp)
  
  df.list <- mapply(single.mean, df.list, scen.list, boosted, SIMPLIFY = FALSE)

  combined <- df.list %>%
    reduce(full_join, by='time')

  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
    geom_line() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12 MCS', subtitle = 'Treated Population') +
    xlab('Year') +
    ylab('Difference')
  
  print(p1)
}

SF12.change.treated.batch <- function(df.list, scen.list) {
  batch.mean <- function(data, scen, boosted) {
    # define varname
    newvar.name <- paste0(scen, '.SF12')
    # prepare data
    data <- data %>%
      select(pidp, time, weight, run_id, SF_12) %>%
      filter(pidp %in% boosted) %>%
      group_by(time, run_id) %>%
      summarise(!!newvar.name := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  #TODO: FIX THIS! NEED DIFFERENT BASELINE FOR EACH INT?? THINK SO!
  # NEED A FUNCTION TO DO THE DIFF CALCULATION AND ANOTHER TO RUN IT THROUGH
  # EACH DF
  # get boosted pidps
  boosted <- df.list[[2]] %>%
    select(pidp, income_boosted) %>%
    filter(income_boosted == 'True')
  
  df.list <- mapply(single.mean, df.list, scen.list, boosted, SIMPLIFY = FALSE)
  
  combined <- df.list %>%
    reduce(full_join, by=c('time', 'run_id'))

  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
    geom_smooth() +
    geom_hline(yintercept = 0, linetype='dashed') +
    labs(title = 'Relative change in SF12 MCS', subtitle = 'Treated Population') +
    xlab('Year') +
    ylab('Difference')
  
  print(p1)
}
```

```{r SF12_deciles, echo=FALSE}
SF12.by.simd.deciles <- function(df.list, scen.list, start.year = 2020, batch=FALSE) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, simd_decile, SF_12) %>%
      filter(time >= start.year) %>%
      group_by(time, simd_decile) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, simd_decile, run_id, SF_12) %>%
      filter(time >= start.year) %>%
      group_by(time, simd_decile, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'simd_decile', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'simd_decile'))
  }
  
  combined$simd_decile <- as.factor(combined$simd_decile)
  
  int.labels <- scen.list[-1]
  
  for (int in int.labels) {
    int.name <- paste0(int, '.SF12')
    if (batch) {
      p1 <- ggplot(combined, aes(x = time, group = simd_decile, colour = simd_decile)) +
        geom_smooth(aes(y = base.SF12)) +
        geom_smooth(aes(y = .data[[int.name]]), linetype='dashed') +
        labs(title = 'SF12 MCS Deciles', subtitle = paste0('Baseline vs ', int)) +
        xlab('Year') +
        ylab('Difference')
    } else {
      p1 <- ggplot(combined, aes(x = time, group = simd_decile, colour = simd_decile)) +
        geom_line(aes(y = base.SF12)) +
        geom_line(aes(y = .data[[int.name]]), linetype='dashed') +
        labs(title = 'SF12 MCS Deciles', subtitle = int) +
        xlab('Year') +
        ylab('Difference')
    }
    print(p1)
  }
}
```

```{r SF_change_deciles, echo=FALSE}
SF12.change.by.deciles <- function(df.list, scen.list, start.year = 2020, batch = FALSE) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, simd_decile, SF_12) %>%
      filter(time >= start.year) %>%
      group_by(time, simd_decile) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, simd_decile, run_id, SF_12) %>%
      filter(time >= start.year) %>%
      group_by(time, simd_decile, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'simd_decile', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'simd_decile'))
  }
  
  combined$simd_decile <- as.factor(combined$simd_decile)
  
  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, simd_decile, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))
  
  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  if (batch) {
    p1 <- ggplot(combined, aes(x = time, y = diff, group = simd_decile, colour = simd_decile)) +
      geom_smooth() +
      geom_hline(yintercept = 0, linetype='dashed') +
      facet_wrap(. ~ scen, ncol=1) +
      labs(title = 'Relative change in SF12 MCS', subtitle = 'Whole population') +
      xlab('Year') +
      ylab('Difference')
  } else {
    p1 <- ggplot(combined, aes(x = time, y = diff, group = simd_decile, colour = simd_decile)) +
      geom_line() +
      geom_hline(yintercept = 0, linetype='dashed') +
      facet_wrap(. ~ scen, ncol=1) +
      labs(title = 'Relative change in SF12 MCS', subtitle = 'Whole population') +
      xlab('Year') +
      ylab('Difference')
  }
  
  ggsave(filename = 'test_plot.png',
         plot = p1,
         path = here::here('plots', 'SCOTGOVWORK'),
         width = 9,
         height = 20)
  
  print(p1)
}
```


# PLOTS

## MCS - Whole Population

```{r}
if (batch) {
  SF12.change.full.sample.batch(int.list, scen.list)
} else {
  SF12.change.full.sample.single(int.list, scen.list)
}
```

## MCS - Households with Children

```{r}
if (batch) {
  SF12.change.families.batch(int.list, scen.list)
} else {
  SF12.change.families.single(int.list, scen.list)
}
```

## MCS - Treatment on Treated

```{r}
if (batch) {
  SF12.change.treated.batch(int.list, scen.list)
} else {
  SF12.change.treated.single(int.list, scen.list)
}
```




## MCS - DECILES

```{r}
SF12.by.simd.deciles(int.list, scen.list)
```

```{r}
SF12.by.simd.deciles(int.list, scen.list, start.year = 2024, batch = FALSE)
```


## MCS - CHANGE BY DECILES

```{r}
SF12.change.by.deciles(int.list, scen.list)
```


## MCS - PRIORITY GROUPS

### All Priority Subgroups

```{r}

```

### Minority Ethnic Groups

```{r}
priority_filter_ethnicity <- function(df.list, scen.list, start.year) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, ethnicity, SF_12) %>%
      filter(ethnicity != 'WBI') %>%
      group_by(time) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, ethnicity, run_id, SF_12) %>%
      filter(ethnicity != 'WBI') %>%
      group_by(time, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time'))
  }
  return(combined)
}

priority_filter_child_under_one <- function(df.list, scen.list, start.year) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, child_ages, SF_12) %>%
      filter(substr(child_ages, 1, 1) == 0) %>%
      group_by(time) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, child_ages, run_id, SF_12) %>%
      filter(substr(child_ages, 1, 1) == 0) %>%
      group_by(time, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time'))
  }
  return(combined)
}

priority_filter_three_plus_children <- function(df.list, scen.list, start.year) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, nkids, SF_12) %>%
      filter(nkids >= 3) %>%
      group_by(time) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, nkids, run_id, SF_12) %>%
      filter(nkids >= 3) %>%
      group_by(time, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time'))
  }
  return(combined)
}

priority_filter_mother_under_25 <- function(df.list, scen.list, start.year) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, age, nkids_ind, SF_12) %>%
      filter(nkids_ind > 0 & age < 25) %>%
      group_by(time) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, weight, age, nkids_ind, run_id, SF_12) %>%
      filter((nkids_ind > 0) && (age < 25)) %>%
      group_by(time, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time'))
  }
  return(combined)
}

priority_filter_disabled <- function(df.list, scen.list, start.year) {
  single.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, hidp, weight, S7_labour_state, SF_12) %>%
      group_by(hidp) %>%
      mutate(disabled_flag = ifelse(any(S7_labour_state) == 'disabled')) %>%
      filter(disabled_flag == TRUE) %>%
      group_by(time) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  batch.mean <- function(data, scen, start.year) {
    newvar.name <- paste0(scen, '.SF12')
    data <- data %>%
      select(time, hidp, weight, S7_labour_state, run_id, SF_12) %>%
      group_by(hidp) %>%
      mutate(disabled_flag = ifelse(any(S7_labour_state) == 'disabled')) %>%
      filter(disabled_flag == TRUE) %>%
      group_by(time, run_id) %>%
      summarise(!!sym(newvar.name) := weighted.mean(SF_12, w = weight))
    return(data)
  }
  
  if (batch) {
    mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time', 'run_id'))
  } else {
    mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE)
    combined <- mod.list %>%
      reduce(full_join, by=c('time'))
  }
  return(combined)
}

SF12.change.priority.group <- function(df.list, scen.list, priority.group, start.year = 2020, batch=FALSE) {
  
  # Filter data for priority groups
  if (priority.group == 'minority_ethnic') { combined <- priority_filter_ethnicity(df.list, scen.list, start.year) }
  if (priority.group == 'child_under_one') { combined <- priority_filter_child_under_one(df.list, scen.list, start.year) }
  if (priority.group == 'three_plus_children') { combined <- priority_filter_three_plus_children(df.list, scen.list, start.year) }
  if (priority.group == 'mother_under_25') { combined <- priority_filter_mother_under_25(df.list, scen.list, start.year) }
  if (priority.group == 'disabled') { combined <- priority_filter_disabled(df.list, scen.list, start.year) }
  
  # List of intervention columns
  int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE)
  
  # Create the new dataframe with differences
  combined <- combined %>%
    mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>%
    select(time, starts_with("diff")) %>%
    rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1"))

  combined <- combined %>%
    pivot_longer(cols = starts_with('diff'),
                 names_to = 'scen',
                 values_to = 'diff')
  
  if (batch) {
    p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
      geom_smooth() +
      geom_hline(yintercept = 0, linetype='dashed') +
      labs(title = paste0('SF12 MCS Change - ', priority.group)) +
      xlab('Year') +
      ylab('Difference')
  } else {
    p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) +
      geom_line() +
      geom_hline(yintercept = 0, linetype='dashed') +
      labs(title = paste0('SF12 MCS Change - ', priority.group)) +
      xlab('Year') +
      ylab('Difference')
  }
  
  print(p1)
}


batch <- FALSE
start.year <- 2020


SF12.change.priority.group(int.list, scen.list, priority.group = 'minority_ethnic')
SF12.change.priority.group(int.list, scen.list, priority.group = 'child_under_one')
SF12.change.priority.group(int.list, scen.list, priority.group = 'three_plus_children')
SF12.change.priority.group(int.list, scen.list, priority.group = 'mother_under_25')
#SF12.change.priority.group(int.list, scen.list, priority.group = 'disabled')


```


# Poverty Statistics

See how interventions affect child poverty.

## Relative Poverty

```{r}
# First need the relative poverty thresholds from baseline
threshold <- base %>%
  select(time, weight, hh_income) %>%
  group_by(time) %>%
  summarise(poverty_threshold = (weighted.mean(hh_income, w = weight) * 0.6))

ggplot(data = threshold, aes(x = time, y = poverty_threshold)) +
  geom_col() +
  labs(title = 'Relative poverty threshold over time') +
  xlab('Year') +
  ylab('Threshold')
```

```{r}
int25.test <- merge(int25, threshold, by = 'time')
# Now calculate number of households and number of children below threshold
hh_boosted <- int25.test %>%
  select(hidp, time, hh_income, income_boosted, boost_amount, nkids, poverty_threshold) %>%
  filter(income_boosted == 'True') %>%
  filter(hh_income < poverty_threshold) %>%
  group_by(time) %>%
  summarise(n = n(),
            n_boosted = length(unique(hidp)),
            total_boost = sum(boost_amount),
            kids_boosted = sum(nkids)) %>%
  mutate(prop_boosted = n_boosted / n,
         prop_kids_boosted)

p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) +
  geom_line() +
  labs(title = 'Number of households receiving intervention', subtitle = int.name) +
  xlab('Year') +
  ylab('Number Boosted')
print(p1)

p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) +
  geom_line() +
  labs(title = 'Number of children in households receiving intervention', subtitle = int.name) +
  xlab('Year') +
  ylab('Number Children')
print(p2)
```


# DIAGNOSTICS

```{r}
intervention_information_single <- function(int.dat, int.name, target.year) {
  hh_boosted <- int.dat %>%
    select(hidp, time, income_boosted, boost_amount, nkids) %>%
    filter(income_boosted == 'True') %>%
    group_by(time) %>%
    summarise(n_boosted = length(unique(hidp)),
              total_boost = sum(boost_amount),
              kids_boosted = sum(nkids))
  
  p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Number of households receiving intervention', subtitle = int.name) +
    xlab('Year') +
    ylab('Number Boosted')
  
  p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Number of children in households receiving intervention', subtitle = int.name) +
    xlab('Year') +
    ylab('Number Children')
  
  p3 <- ggplot(hh_boosted, aes(x = time, y = total_boost)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Total boost amount', subtitle = int.name) +
    xlab('Year') +
    ylab('Boost Amount')
  
  mean.boost <- int.dat %>%
    select(time, income_boosted, boost_amount) %>%
    group_by(time, income_boosted) %>%
    summarise(mean_boost = mean(boost_amount)) %>%
    filter(income_boosted == 'True')
  
  p4 <- ggplot(mean.boost, aes(x = time, y = mean_boost)) +
    geom_line() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Mean boost amount', subtitle = int.name) +
    xlab('Year') +
    ylab('Boost Amount')
  
  print(p1)
  print(p2)
  print(p3)
  print(p4)
}

intervention_information_batch <- function(int.dat, int.name, target.year) {
  hh_boosted <- int.dat %>%
    select(hidp, time, run_id, income_boosted, boost_amount, nkids) %>%
    filter(income_boosted == 'True') %>%
    group_by(time, run_id) %>%
    summarise(n_boosted = length(unique(hidp)),
              total_boost = sum(boost_amount),
              kids_boosted = sum(nkids))
  
  p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) +
    geom_smooth() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Number of households receiving intervention', subtitle = int.name) +
    xlab('Year') +
    ylab('Number Boosted')
  
  p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) +
    geom_smooth() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Number of children in households receiving intervention', subtitle = int.name) +
    xlab('Year') +
    ylab('Number Children')
  
  p3 <- ggplot(hh_boosted, aes(x = time, y = total_boost)) +
    geom_smooth() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Total boost amount', subtitle = int.name) +
    xlab('Year') +
    ylab('Boost Amount')
  
  mean.boost <- int.dat %>%
    select(time, income_boosted, boost_amount) %>%
    group_by(time, run_id, income_boosted) %>%
    summarise(mean_boost = mean(boost_amount)) %>%
    filter(income_boosted == 'True')
  
  p4 <- ggplot(mean.boost, aes(x = time, y = mean_boost)) +
    geom_smooth() +
    geom_vline(xintercept = target.year, linetype = 'dashed') +
    labs(title = 'Mean boost amount', subtitle = int.name) +
    xlab('Year') +
    ylab('Boost Amount')
  
  print(p1)
  print(p2)
  print(p3)
  print(p4)
}
```

## 25

```{r}
if (batch) {
  intervention_information_batch(int25, int.name = 'int25', target.year = 2030)
} else {
  intervention_information_single(int25, int.name = 'int25', target.year = 2030)
}
```

## 30

```{r}
if (batch) {
  intervention_information_batch(int30, int.name = 'int30', target.year = 2030)
} else {
  intervention_information_single(int30, int.name = 'int30', target.year = 2030)
}
```

## 35

```{r}
if (batch) {
  intervention_information_batch(int35, int.name = 'int35', target.year = 2030)
} else {
  intervention_information_single(int35, int.name = 'int35', target.year = 2030)
}
```

## 40

```{r}
if (batch) {
  intervention_information_batch(int40, int.name = 'int40', target.year = 2030)
} else {
  intervention_information_single(int40, int.name = 'int40', target.year = 2030)
}
```

## 45

```{r}
if (batch) {
  intervention_information_batch(int45, int.name = 'int45', target.year = 2030)
} else {
  intervention_information_single(int45, int.name = 'int45', target.year = 2030)
}
```

## 50

```{r}
if (batch) {
  intervention_information_batch(int50, int.name = 'int50', target.year = 2030)
} else {
  intervention_information_single(int50, int.name = 'int50', target.year = 2030)
}
```


# TESTING


```{r}
```

