---
title: "Scottish Child Payment Interventions"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

# SETUP

```{r "setup", include=FALSE}

require(tidyverse)
require(ggplot2)
require(knitr)
require(here)
require(dplyr)
require(tidyr)
require(purrr)
require(parallel)

#workingDir <- "/home/luke/Documents/WORK/MINOS/"
workingDir <- normalizePath('../')
knitr::opts_knit$set(root.dir = workingDir)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE
)
rm(workingDir)
```

Source utils for some functions.

```{r source_functions, include=FALSE}
source(here::here('minos', 'utils_datain.R'))
```


```{r read_data}
#out.path <- here::here('output', 'default_config')
#out.path <- here::here('output', 'glasgow_scaled')
#out.path <- here::here('output', 'scaled_scotland')
#out.path <- here::here('output', 'default_config_batch')
out.path <- here::here('output', 'scaled_scotland_10', 'summary_files')


# Whole population summaries
allpop.files <- list.files(out.path,
                           pattern = "*_whole_pop_summary.csv",
                           full.names = TRUE)
allpop <- do.call(rbind, lapply(allpop.files, read.csv))
allpop <- allpop %>% select(-X)
rm(allpop.files)

# Families with children
families.files <- list.files(out.path,
                           pattern = "*_families_summary.csv",
                           full.names = TRUE)
families <- do.call(rbind, lapply(families.files, read.csv))
families <- families %>% select(-X)
rm(families.files)

# Treatment on Treated
treated.files <- list.files(out.path,
                           pattern = "*_treated_summary.csv",
                           full.names = TRUE)
treated <- do.call(rbind, lapply(treated.files, read.csv))
treated <- treated %>% select(-X)
rm(treated.files)

# SIMD Deciles
simd_decile.files <- list.files(out.path,
                           pattern = "*_simd_decile_summary.csv",
                           full.names = TRUE)
simd_decile <- do.call(rbind, lapply(simd_decile.files, read.csv))
simd_decile <- simd_decile %>% select(-X)
rm(simd_decile.files)


# Save path and save flag
save.path <- here::here('plots', 'SCOTGOV', 'SPC')
create.if.not.exists(save.path)
shall.we.save <- FALSE
plot.width <- 10
plot.height <- 5
```

# SF12 Change

## Whole Pop

```{r}
allpop.plot <- allpop %>%
  select(run_id, time, scenario, SF_12) %>%
  pivot_wider(names_from = scenario,
              values_from = SF_12) %>%
  mutate(across(ends_with("UniversalCredit"), ~ . - baseline, .names = "diff_{col}")) %>%
  select(run_id, time, starts_with('diff_')) %>%
  pivot_longer(cols = starts_with('diff_'),
               names_to = 'Intervention',
               names_prefix = 'diff_',
               values_to = 'SF_12_change')

ggplot(allpop.plot, aes(x = time, y = SF_12_change, group = Intervention, colour = Intervention)) +
  geom_smooth() +
  geom_hline(yintercept = 0, linetype = 'dashed')

```

## Families

```{r}
fam.plot <- families %>%
  select(run_id, time, scenario, SF_12) %>%
  pivot_wider(names_from = scenario,
              values_from = SF_12) %>%
  mutate(across(ends_with("UniversalCredit"), ~ . - baseline, .names = "diff_{col}")) %>%
  select(run_id, time, starts_with('diff_')) %>%
  pivot_longer(cols = starts_with('diff_'),
               names_to = 'Intervention',
               names_prefix = 'diff_',
               values_to = 'SF_12_change')

ggplot(fam.plot, aes(x = time, y = SF_12_change, group = Intervention, colour = Intervention)) +
  geom_smooth() +
  geom_hline(yintercept = 0, linetype = 'dashed')

```

## Treated

```{r}
treated.plot <- treated %>%
  select(run_id, time, scenario, SF_12) %>%
  pivot_wider(names_from = scenario,
              values_from = SF_12) %>%
  mutate(across(ends_with("UniversalCredit"), ~ . - baseline, .names = "diff_{col}")) %>%
  select(run_id, time, starts_with('diff_')) %>%
  pivot_longer(cols = starts_with('diff_'),
               names_to = 'Intervention',
               names_prefix = 'diff_',
               values_to = 'SF_12_change')

ggplot(treated.plot, aes(x = time, y = SF_12_change, group = Intervention, colour = Intervention)) +
  geom_smooth() +
  geom_hline(yintercept = 0, linetype = 'dashed')

```

## SIMD Deciles

```{r}
simd_decile.plot <- simd_decile %>%
  select(run_id, time, scenario, simd_decile, SF_12) %>%
  pivot_wider(names_from = scenario,
              values_from = SF_12) %>%
  mutate(across(ends_with("UniversalCredit"), ~ . - baseline, .names = "diff_{col}")) %>%
  select(run_id, time, simd_decile, starts_with('diff_')) %>%
  pivot_longer(cols = starts_with('diff_'),
               names_to = 'Intervention',
               names_prefix = 'diff_',
               values_to = 'SF_12_change')
simd_decile.plot$simd_decile <- as.factor(simd_decile.plot$simd_decile)

# for (i in 1:10) {
#   p1 <- ggplot(filter(simd_decile.plot, simd_decile == i), aes(x = time, y = SF_12_change, group = Intervention, colour = Intervention)) +
#     geom_smooth() +
#     geom_hline(yintercept = 0, linetype = 'dashed') +
#     labs(title = 'SF_12 Change', subtitle = paste0('SIMD Decile ', i))
#   print(p1)
# }

p2 <- ggplot(simd_decile.plot, aes(x = time, y = SF_12_change, group = Intervention, colour = Intervention)) +
  geom_smooth() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  facet_wrap(. ~ simd_decile) +
  labs(title = 'SF_12 Change', subtitle = 'By Decile')
print(p2)

p3 <- ggplot(simd_decile.plot, aes(x = time, y = SF_12_change, group = simd_decile, colour = simd_decile)) +
  geom_smooth() +
  geom_hline(yintercept = 0, linetype = 'dashed') +
  facet_wrap(. ~ Intervention) +
  labs(title = 'SF_12 Change All Deciles', subtitle = 'By Intervention')
print(p3)
```

<!-- # MCS - PRIORITY GROUPS -->

<!-- ## All Priority Subgroups -->

<!-- ```{r} -->

<!-- ``` -->

<!-- ## Minority Ethnic Groups -->

<!-- ```{r} -->
<!-- priority_filter_ethnicity <- function(df.list, scen.list, start.year) { -->
<!--   single.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, ethnicity, SF_12) %>% -->
<!--       filter(ethnicity != 'WBI') %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->
<!--   batch.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, ethnicity, run_id, SF_12) %>% -->
<!--       filter(ethnicity != 'WBI') %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time, run_id) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->

<!--   if (batch) { -->
<!--     mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time', 'run_id')) -->
<!--   } else { -->
<!--     mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time')) -->
<!--   } -->
<!--   return(combined) -->
<!-- } -->

<!-- priority_filter_child_under_one <- function(df.list, scen.list, start.year) { -->
<!--   single.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, child_under_one, SF_12) %>% -->
<!--       filter(child_under_one == TRUE) %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->
<!--   batch.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, child_under_one, run_id, SF_12) %>% -->
<!--       filter(child_under_one == TRUE) %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time, run_id) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->

<!--   if (batch) { -->
<!--     mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time', 'run_id')) -->
<!--   } else { -->
<!--     mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time')) -->
<!--   } -->
<!--   return(combined) -->
<!-- } -->

<!-- priority_filter_three_plus_children <- function(df.list, scen.list, start.year) { -->
<!--   single.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, three_plus_child, SF_12) %>% -->
<!--       filter(three_plus_child == TRUE) %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->
<!--   batch.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, three_plus_child, run_id, SF_12) %>% -->
<!--       filter(three_plus_child) %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time, run_id) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->

<!--   if (batch) { -->
<!--     mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time', 'run_id')) -->
<!--   } else { -->
<!--     mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time')) -->
<!--   } -->
<!--   return(combined) -->
<!-- } -->

<!-- priority_filter_mother_under_25 <- function(df.list, scen.list, start.year) { -->
<!--   single.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, mother_under_25, SF_12) %>% -->
<!--       filter(mother_under_25 == TRUE) %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->
<!--   batch.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, mother_under_25, run_id, SF_12) %>% -->
<!--       filter(mother_under_25 == TRUE) %>% -->
<!--       filter(SF_12 >= 0) %>% -->
<!--       group_by(time, run_id) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->

<!--   if (batch) { -->
<!--     mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time', 'run_id')) -->
<!--   } else { -->
<!--     mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time')) -->
<!--   } -->
<!--   return(combined) -->
<!-- } -->

<!-- priority_filter_disabled <- function(df.list, scen.list, start.year) { -->
<!--   single.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, hidp, S7_labour_state, SF_12) %>% -->
<!--       group_by(hidp) %>% -->
<!--       mutate(disabled_flag = ifelse(any(S7_labour_state) == 'disabled')) %>% -->
<!--       filter(disabled_flag == TRUE) %>% -->
<!--       group_by(time) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->
<!--   batch.mean <- function(data, scen, start.year) { -->
<!--     newvar.name <- paste0(scen, '.SF12') -->
<!--     data <- data %>% -->
<!--       select(time, hidp, S7_labour_state, run_id, SF_12) %>% -->
<!--       group_by(hidp) %>% -->
<!--       mutate(disabled_flag = ifelse(any(S7_labour_state) == 'disabled')) %>% -->
<!--       filter(disabled_flag == TRUE) %>% -->
<!--       group_by(time, run_id) %>% -->
<!--       summarise(!!sym(newvar.name) := mean(SF_12, na.rm = TRUE)) -->
<!--     return(data) -->
<!--   } -->

<!--   if (batch) { -->
<!--     mod.list <- mapply(batch.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time', 'run_id')) -->
<!--   } else { -->
<!--     mod.list <- mapply(single.mean, int.list, scen.list, start.year, SIMPLIFY = FALSE) -->
<!--     combined <- mod.list %>% -->
<!--       reduce(full_join, by=c('time')) -->
<!--   } -->
<!--   return(combined) -->
<!-- } -->

<!-- SF12.change.priority.group <- function(df.list, scen.list, priority.group, start.year = 2020, batch=FALSE) { -->

<!--   # Filter data for priority groups -->
<!--   if (priority.group == 'minority_ethnic') { combined <- priority_filter_ethnicity(df.list, scen.list, start.year) } -->
<!--   if (priority.group == 'child_under_one') { combined <- priority_filter_child_under_one(df.list, scen.list, start.year) } -->
<!--   if (priority.group == 'three_plus_children') { combined <- priority_filter_three_plus_children(df.list, scen.list, start.year) } -->
<!--   if (priority.group == 'mother_under_25') { combined <- priority_filter_mother_under_25(df.list, scen.list, start.year) } -->
<!--   if (priority.group == 'disabled') { combined <- priority_filter_disabled(df.list, scen.list, start.year) } -->

<!--   # List of intervention columns -->
<!--   int_cols <- grep("int\\d+.SF12", names(combined), value = TRUE) -->

<!--   # Create the new dataframe with differences -->
<!--   combined <- combined %>% -->
<!--     mutate(across(all_of(int_cols), ~ . - base.SF12, .names = "diff{col}")) %>% -->
<!--     select(time, starts_with("diff")) %>% -->
<!--     rename_with(~ str_replace_all(., "diffint(\\d+).SF12", "diff\\1")) -->

<!--   combined <- combined %>% -->
<!--     pivot_longer(cols = starts_with('diff'), -->
<!--                  names_to = 'scen', -->
<!--                  values_to = 'diff') -->

<!--   if (batch) { -->
<!--     p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) + -->
<!--       geom_smooth() + -->
<!--       geom_hline(yintercept = 0, linetype='dashed') + -->
<!--       labs(title = paste0('SF12 MCS Change - ', priority.group)) + -->
<!--       xlab('Year') + -->
<!--       ylab('Difference') -->
<!--   } else { -->
<!--     p1 <- ggplot(combined, aes(x = time, y = diff, group = scen, colour = scen)) + -->
<!--       geom_line() + -->
<!--       geom_hline(yintercept = 0, linetype='dashed') + -->
<!--       labs(title = paste0('SF12 MCS Change - ', priority.group)) + -->
<!--       xlab('Year') + -->
<!--       ylab('Difference') -->
<!--   } -->

<!--   print(p1) -->
<!-- } -->


<!-- batch <- FALSE -->
<!-- start.year <- 2020 -->


<!-- SF12.change.priority.group(int.list, scen.list, priority.group = 'minority_ethnic', batch = batch) -->
<!-- SF12.change.priority.group(int.list, scen.list, priority.group = 'child_under_one', batch = batch) -->
<!-- SF12.change.priority.group(int.list, scen.list, priority.group = 'three_plus_children', batch = batch) -->
<!-- SF12.change.priority.group(int.list, scen.list, priority.group = 'mother_under_25', batch = batch) -->
<!-- #SF12.change.priority.group(int.list, scen.list, priority.group = 'disabled', batch = batch) -->


<!-- ``` -->


<!-- # Poverty Statistics -->

<!-- See how interventions affect child poverty. -->

<!-- ## Relative Poverty -->

<!-- ```{r} -->
<!-- # First need the relative poverty thresholds from baseline -->
<!-- threshold <- base %>% -->
<!--   select(time, hh_income) %>% -->
<!--   group_by(time) %>% -->
<!--   summarise(poverty_threshold = (mean(hh_income, na.rm = TRUE) * 0.6)) -->

<!-- ggplot(data = threshold, aes(x = time, y = poverty_threshold)) + -->
<!--   geom_col() + -->
<!--   labs(title = 'Relative poverty threshold over time') + -->
<!--   xlab('Year') + -->
<!--   ylab('Threshold') -->
<!-- ``` -->

<!-- ```{r} -->
<!-- int25.test <- merge(int25, threshold, by = 'time') -->
<!-- # Now calculate number of households and number of children below threshold -->
<!-- hh_boosted <- int25.test %>% -->
<!--   select(hidp, time, hh_income, income_boosted, boost_amount, nkids, poverty_threshold) %>% -->
<!--   filter(income_boosted == 'True') %>% -->
<!--   filter(hh_income < poverty_threshold) %>% -->
<!--   group_by(time) %>% -->
<!--   summarise(n = n(), -->
<!--             n_boosted = length(unique(hidp)), -->
<!--             total_boost = sum(boost_amount), -->
<!--             kids_boosted = sum(nkids)) %>% -->
<!--   mutate(prop_boosted = n_boosted / n) -->

<!-- p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) + -->
<!--   geom_line() + -->
<!--   labs(title = 'Number of households receiving intervention') + -->
<!--   xlab('Year') + -->
<!--   ylab('Number Boosted') -->
<!-- print(p1) -->

<!-- p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) + -->
<!--   geom_line() + -->
<!--   labs(title = 'Number of children in households receiving intervention') + -->
<!--   xlab('Year') + -->
<!--   ylab('Number Children') -->
<!-- print(p2) -->
<!-- ``` -->


<!-- # DIAGNOSTICS -->

<!-- ```{r} -->
<!-- intervention_information_single <- function(int.dat, int.name, target.year) { -->
<!--   hh_boosted <- int.dat %>% -->
<!--     select(hidp, time, income_boosted, boost_amount, nkids) %>% -->
<!--     filter(income_boosted == 'True') %>% -->
<!--     group_by(time) %>% -->
<!--     summarise(n_boosted = length(unique(hidp)), -->
<!--               total_boost = sum(boost_amount), -->
<!--               kids_boosted = sum(nkids)) -->

<!--   p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) + -->
<!--     geom_line() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Number of households receiving intervention', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Number Boosted') -->

<!--   p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) + -->
<!--     geom_line() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Number of children in households receiving intervention', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Number Children') -->

<!--   p3 <- ggplot(hh_boosted, aes(x = time, y = total_boost)) + -->
<!--     geom_line() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Total boost amount', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Boost Amount') -->

<!--   mean.boost <- int.dat %>% -->
<!--     select(time, income_boosted, boost_amount) %>% -->
<!--     group_by(time, income_boosted) %>% -->
<!--     summarise(mean_boost = mean(boost_amount)) %>% -->
<!--     filter(income_boosted == 'True') -->

<!--   p4 <- ggplot(mean.boost, aes(x = time, y = mean_boost)) + -->
<!--     geom_line() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Mean boost amount', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Boost Amount') -->

<!--   print(p1) -->
<!--   print(p2) -->
<!--   print(p3) -->
<!--   print(p4) -->
<!-- } -->

<!-- intervention_information_batch <- function(int.dat, int.name, target.year) { -->
<!--   hh_boosted <- int.dat %>% -->
<!--     select(time, run_id, boosted, boost_amount, nkids) %>% -->
<!--     filter(income_boosted == 'True') %>% -->
<!--     group_by(time, run_id) %>% -->
<!--     summarise(n_boosted = length(unique(hidp)), -->
<!--               total_boost = sum(boost_amount), -->
<!--               kids_boosted = sum(nkids)) -->

<!--   p1 <- ggplot(hh_boosted, aes(x = time, y = n_boosted)) + -->
<!--     geom_smooth() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Number of households receiving intervention', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Number Boosted') -->

<!--   p2 <- ggplot(hh_boosted, aes(x = time, y = kids_boosted)) + -->
<!--     geom_smooth() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Number of children in households receiving intervention', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Number Children') -->

<!--   p3 <- ggplot(hh_boosted, aes(x = time, y = total_boost)) + -->
<!--     geom_smooth() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Total boost amount', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Boost Amount') -->

<!--   mean.boost <- int.dat %>% -->
<!--     select(time, income_boosted, boost_amount) %>% -->
<!--     group_by(time, run_id, income_boosted) %>% -->
<!--     summarise(mean_boost = mean(boost_amount)) %>% -->
<!--     filter(income_boosted == 'True') -->

<!--   p4 <- ggplot(mean.boost, aes(x = time, y = mean_boost)) + -->
<!--     geom_smooth() + -->
<!--     geom_vline(xintercept = target.year, linetype = 'dashed') + -->
<!--     labs(title = 'Mean boost amount', subtitle = int.name) + -->
<!--     xlab('Year') + -->
<!--     ylab('Boost Amount') -->

<!--   print(p1) -->
<!--   print(p2) -->
<!--   print(p3) -->
<!--   print(p4) -->
<!-- } -->
<!-- ``` -->

<!-- ## 25 -->

<!-- ```{r} -->
<!-- # if (batch) { -->
<!-- #   intervention_information_batch(int25, int.name = 'int25', target.year = 2030) -->
<!-- # } else { -->
<!-- #   intervention_information_single(int25, int.name = 'int25', target.year = 2030) -->
<!-- # } -->
<!-- ``` -->

<!-- ## 30 -->

<!-- ```{r} -->
<!-- # if (batch) { -->
<!-- #   intervention_information_batch(int30, int.name = 'int30', target.year = 2030) -->
<!-- # } else { -->
<!-- #   intervention_information_single(int30, int.name = 'int30', target.year = 2030) -->
<!-- # } -->
<!-- ``` -->

<!-- ## 35 -->

<!-- ```{r} -->
<!-- # if (batch) { -->
<!-- #   intervention_information_batch(int35, int.name = 'int35', target.year = 2030) -->
<!-- # } else { -->
<!-- #   intervention_information_single(int35, int.name = 'int35', target.year = 2030) -->
<!-- # } -->
<!-- ``` -->

<!-- ## 40 -->

<!-- ```{r} -->
<!-- # if (batch) { -->
<!-- #   intervention_information_batch(int40, int.name = 'int40', target.year = 2030) -->
<!-- # } else { -->
<!-- #   intervention_information_single(int40, int.name = 'int40', target.year = 2030) -->
<!-- # } -->
<!-- ``` -->

<!-- ## 45 -->

<!-- ```{r} -->
<!-- # if (batch) { -->
<!-- #   intervention_information_batch(int45, int.name = 'int45', target.year = 2030) -->
<!-- # } else { -->
<!-- #   intervention_information_single(int45, int.name = 'int45', target.year = 2030) -->
<!-- # } -->
<!-- ``` -->

<!-- ## 50 -->

<!-- ```{r} -->
<!-- # if (batch) { -->
<!-- #   intervention_information_batch(int50, int.name = 'int50', target.year = 2030) -->
<!-- # } else { -->
<!-- #   intervention_information_single(int50, int.name = 'int50', target.year = 2030) -->
<!-- # } -->
<!-- ``` -->


<!-- # TESTING -->


<!-- ```{r} -->
<!-- ``` -->

