randomness:
    key_columns: ['entrance_time', 'age']
time:
    start: {year: 2020, month: 10, day: 15}
    end:   {year: 2035, month: 10, day: 15}
    step_size: 365.25  # Days
    num_years: 15
population:
    age_start: 0
    age_end: 100

parity: False

input_data_dir: "data/final_US"
persistent_data_dir: "persistent_data"
output_data_dir: "output"

transition_dir: 'data/transitions'
replenishing_dir: 'data/replenishing'

cross_validation: FALSE
synthetic: FALSE
scotland: FALSE

# Correct ordering of components is automated in RunPipeline, so can be passed in any order here
#components : [lmmYJMWB(), Loneliness(), Tobacco(), S7Labour(), HourlyWage(), JobSec(), Neighbourhood(), Housing(), lmmYJNutrition(), lmmYJIncome(), Education(), Ageing(), Mortality(), nkidsFertilityAgeSpecificRates(), Replenishment()]
components : [Ageing(), Mortality(), nkidsFertilityAgeSpecificRates(), Replenishment()]


scale_rates:
    method: "constant"
    constant:
        education: 1
        mortality: 1
        fertility: 1

