randomness:
    key_columns: ['entrance_time', 'age']
time:
    start: {year: 2020, month: 10, day: 15}
    end:   {year: 2035, month: 10, day: 15}
    step_size: 365.25  # Days
    num_years: 15
population:
    age_start: 0
    age_end: 100

mortality_file: 'regional_mortality_2011_2061.csv'
fertility_file: 'regional_fertility_2011_2061.csv'

input_data_dir: "data/final_US"
persistent_data_dir: "persistent_data"
output_data_dir: "output"

transition_dir: 'data/transitions'
replenishing_dir: 'data/replenishing'
cross_validation: FALSE

# Child poverty intervention parameters
#child_poverty_target: 1
#target_year: 2030
#target_poverty_proportion: 0.05
#input_population: 'all'
#target_group: 'all'
#intervention_method: 1
intervention_amount: 25

# Correct ordering of components is automated in RunPipeline, so can be passed in any order here
components : [lmmYJMWB(), Loneliness(), Tobacco(), Neighbourhood(),
              Housing(), lmmYJNutrition(), lmmYJIncome(), Education(),
              Heating(), financialSituation(), MaterialDeprivationChild(), ChildPovertyMetrics(),
              nkidsFertilityAgeSpecificRates(),
              Ageing(), Mortality(),
              Replenishment(),
              ChildPovertyIntervention]

scale_rates:
    method: "constant"
    constant:
        education: 1
        mortality: 1
        fertility: 1

