---
title: "Loneliness"
output: html_document
bibliography: 
  - "`r here::here('docsrc', 'refs.bib')`" # finally figure out how to combine these for debugging and actual 
---

## Loneliness

```{r setup, include=FALSE}
library(here)
library(glmnet)
library(plyr)

source(here::here("docsrc", "documentation", "notebooks", "sphinx_notebook_utils.R"))
model_path <- here::here("data", "transitions", "loneliness", "rfo", "loneliness_RFO.rds")
model <- readRDS(model_path)

data <- read.csv(here::here("data", "final_US", "2020_US_cohort.csv"))
obs <- data$loneliness
data$loneliness_last <- data$loneliness

preds <- ranger::predictions(stats::predict(model, data))
column_names <- colnames(preds)
preds <-glmnet::rmult(preds)
preds <- plyr::mapvalues(preds, from=c(1,2,3), to= column_names)
v <- "loneliness"

```


### Methods

  What methods are used? Justification due to output data type. explanation of model output.
  
```{r loneliness_data}
discrete_barplot(obs, 'loneliness')
```

### Data
  
  What variables are included? Why is this output chosen. What explanatory variables are used and why are they chosen
  
### Results
  
  What are the results. Coefficients tables. diagnostic plots. measures of goodness of fit.


```{r housing_output, echo=FALSE}
options(width=120)
discrete_barplot2(obs, preds, "loneliness") 
rfo_output(model)
```


### References