#######################
# Aspatial model runs #
#######################

################################
# Aspatial Housing Single Runs #
################################

housing_baseline: ### Baseline run of MINOS, using configuration defined in testConfig.yaml
housing_baseline: RUN_CONFIG=config/energy_default.yaml
housing_baseline: MODE=energy_default_config
housing_baseline:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE)

intervention_EPCG:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'EPCG'

intervention_goodHeatingDummy:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'goodHeatingDummy'

intervention_GBIS:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'GBIS'

intervention_EPCG_and_GBIS:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'EPCGandGBIS'

intervention_fossilFuelReplacementScheme:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'fossilFuelReplacementScheme'

#######################################
# ARC4 Aspatial Housing Interventions #
#######################################

aire_housing_baseline: MODE = energy_default_config
aire_housing_baseline: RUN_CONFIG = $(CONFIG)/energy_default.yaml
aire_housing_baseline:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE)

aire_aspatial_goodHeatingDummy: RUN_CONFIG = $(CONFIG)/energy_default.yaml
aire_aspatial_goodHeatingDummy: MODE = energy_default_config
aire_aspatial_goodHeatingDummy:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'goodHeatingDummy'

aire_aspatial_GBIS: RUN_CONFIG = $(CONFIG)/energy_default.yaml
aire_aspatial_GBIS: MODE = energy_default_config
aire_aspatial_GBIS:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'GBIS'

aire_aspatial_FFRS: RUN_CONFIG = $(CONFIG)/energy_default.yaml
aire_aspatial_FFRS: MODE = energy_default_config
aire_aspatial_FFRS:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'fossilFuelReplacementScheme'

###########################
# Manchester Spatial data #
###########################

######################################
# Manchester Individual Housing Runs #
######################################

manchester_housing_baseline: setup_manchester_scaled
manchester_housing_baseline: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
manchester_housing_baseline:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE)

manchester_intervention_goodHeatingDummy: setup_manchester_scaled
manchester_intervention_goodHeatingDummy: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
manchester_intervention_goodHeatingDummy: MODE=energy_manchester_scaled
manchester_intervention_goodHeatingDummy:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'goodHeatingDummy'

manchester_intervention_GBIS: setup_manchester_scaled
manchester_intervention_GBIS: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
manchester_intervention_GBIS: MODE=energy_manchester_scaled
manchester_intervention_GBIS:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'GBIS'

manchester_intervention_fossilFuelReplacementScheme: setup_manchester_scaled
manchester_intervention_fossilFuelReplacementScheme: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
manchester_intervention_fossilFuelReplacementScheme: MODE=energy_manchester_scaled
manchester_intervention_fossilFuelReplacementScheme:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'fossilFuelReplacementScheme'

manchester_intervention_EPCG: setup_manchester_scaled
manchester_intervention_EPCG: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
manchester_intervention_EPCG: MODE=energy_manchester_scaled
manchester_intervention_EPCG:
	$(PYTHON) scripts/run.py -c $(RUN_CONFIG) -o $(MODE) -i 'EPCG'


########################################
# ARC Manchester Housing Interventions #
########################################

aire_manchester_housing_baseline: MODE=energy_manchester_scaled
aire_manchester_housing_baseline: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_housing_baseline:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE)

aire_manchester_noEnergyPriceIncrease: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_noEnergyPriceIncrease: MODE=energy_manchester_scaled
aire_manchester_noEnergyPriceIncrease:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'noEnergyPriceIncrease'


aire_manchester_goodHeatingDummy: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_goodHeatingDummy: MODE=energy_manchester_scaled
aire_manchester_goodHeatingDummy:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'goodHeatingDummy'

aire_manchester_EPCG: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_EPCG: MODE=energy_manchester_scaled
aire_manchester_EPCG:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'EPCG'

aire_manchester_GBIS: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_GBIS: MODE=energy_manchester_scaled
aire_manchester_GBIS:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'GBIS'

aire_manchester_EPCG_and_GBIS: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_EPCG_and_GBIS: MODE=energy_manchester_scaled
aire_manchester_EPCG_and_GBIS:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'EPCGandGBIS'

aire_manchester_FFRS: RUN_CONFIG=$(CONFIG)/energy_manchester_scaled.yaml
aire_manchester_FFRS: MODE=energy_manchester_scaled
aire_manchester_FFRS:
	bash scripts/aire_submit.sh -c $(RUN_CONFIG) -o $(MODE) -i 'fossilFuelReplacementScheme'

aire_all_manchester: aire_manchester_housing_baseline aire_manchester_goodHeatingDummy aire_manchester_EPCG
aire_all_manchester: aire_manchester_GBIS aire_manchester_EPCG_and_GBIS aire_manchester_noEnergyPriceIncrease